### PR TITLE
[monorepo] chore: Adding husky and @jeliasson/husky-hooks

### LINKED ISSUE #14: [monorepo] Implement @jeliasson/npm-husky-hooks
We need to implement [@jeliasson/npm-husky-hooks](https://www.npmjs.com/package/@jeliasson/husky-hooks), a npm package to increase the developer experience and consistency by providing a set of hooks that can be opted-in the development lifecycle.

- [ ]  Install @jeliasson/npm-husky-hooks to monorepo's root
- [ ]  [check-lock-files](https://github.com/jeliasson/npm-husky-hooks#check-lock-files) should only allow pnpm lockfiles
- [ ] [check-branch](https://github.com/jeliasson/npm-husky-hooks#check-branch) should not allow commits to `main`
- [ ] Write something cool about this in README

### PR DESCRIPTION
**Pull request by jeliasson**
Implements [@jeliasson/npm-husky-hooks](https://www.npmjs.com/package/@jeliasson/husky-hooks), a npm package to increase the developer experience and consistency by providing a set of hooks that can be opted-in the development lifecycle.

- [x]  Install @jeliasson/npm-husky-hooks to monorepo's root
- [x] [check-branch](https://github.com/jeliasson/npm-husky-hooks#check-branch) should not allow commits to `main`
- [x]  [check-lock-files](https://github.com/jeliasson/npm-husky-hooks#check-lock-files) should only allow pnpm lockfiles
- [x] Write something cool about how this works in README

### CODE REVIEW

**Comment by kjellberg** [comment]
Thanks @jeliasson. I've updated this issue with a checklist to complete before merge.

**Comment by jeliasson** [comment]
That should do the trick @kjellberg.

**Comment by kjellberg** [comment]
Great! Thanks @jeliasson

**Comment by jeliasson** [comment]
**`check-branch`**
image

**`check-lock-files`**
image

**Pull request merged**
